### ISSUE TITLE
Homebrew install fails on some systems, may be related to master password/managed account

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#60] opened 2016-11-03 12:33 UTC
When bootstrapping and running puppet for the first time on a new Sierra system, I got the below error.

**Basic info:**

- 10.12.1, latest xcode
- puppet-homebrew version 1.5.0
- I'm installing the `homebrew` class as recommended, with my username, and letting it default to the `admin` group. The error still occurs if I set a different group.

**Things about this system that may be causing the problem:**

- My `zbentley` user account is LDAP-linked and managed.
- There is a master password on this system.
- The thing doing the `sudo`-ing is a Ruby wrapper that invokes puppet for me and sudos as necessary (a fork of old Boxen; not sure if it does that any more); not me typing `sudo puppet...` on the shell. All it's doing in Ruby is `system "sudo", "-p", "Password for sudo: ", *args`. Under the covers, it's eventually supplying a `puppet apply` command in `*args`.

**Error text:**

```
Debug: Executing '/usr/bin/su zbentley -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"''
Notice: /Stage[main]/Homebrew::Install/Exec[install-homebrew]/returns: su: Sorry
Error: /usr/bin/su zbentley -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"' returned 1 instead of one of [0]
Error: /Stage[main]/Homebrew::Install/Exec[install-homebrew]/returns: change from notrun to 0 failed: /usr/bin/su zbentley -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"' returned 1 instead of one of [0]
Notice: /Stage[main]/Homebrew::Install/File[/usr/local/bin/brew]: Dependency Exec[install-homebrew] has failures: true
Warning: /Stage[main]/Homebrew::Install/File[/usr/local/bin/brew]: Skipping because of failed dependencies
```

**Things I've tried:**

- Manually doing `sudo su - ` or `sudo -i` to become root, and then running the above command, complete with the `/usr/bin/su zbentley...` stuff. *This works*; the command returns 0 and gets the files.
- Enabling the `root` account and setting the password for it.
- Disabling SIP.
- Working around it: manually installing homebrew myself, then running Puppet. This works, too.

**Ideas:**

The `sorry` message may be caused by the presence of a master password, somehow. If my config is that unique, this is probably not worth the time to fix.

If situations that may cause this are hard/impossible to fix, but easy to detect (e.g. by running a "can su as homebrew user" fact that does `su -c sleep 0`or something and seeing if it works), an error message indicating what the possible causes are could be added? Again, not really your problem.

Add README steps/FAQ entries for how to get around this condition?

**Comment by jordigg** [comment] 2016-11-03 13:25
Seems to be related to the account which runs puppet from that old boxen fork. Which user is that? Which permissions does it have? Is it `root`?

**Comment by zbentley** [comment] 2016-11-03 14:28
The account flow is:

1. `zbentley` (member of `staff`) runs a ruby script.
2. Ruby script runs `sudo -p "prompt string" puppet apply ...`. It's shelling out and running `sudo`, not doing setuid itself.
3. This module runs `su zbentley -c [homebrew install`.

Oddly, if I do `sudo su zbentley`, or if I `sudo su -` into a root shell and then `su zbentley`, it works. If I try to simulate what the script is doing, but without Puppet, it also works: 

```
zbentley~> sudo ruby -e 'system("/usr/bin/su zbentley -c /bin/bash -c echo foo > /Users/zbentley/testfile")'
```

That creates the expected file.

**Comment by zbentley** [comment] 2016-11-23 20:23
I can no longer reproduce this issue on my Mac; I disabled and re-enabled account management, so perhaps something changed?

It seems like a good idea regardless to handle the `su: Sorry` situation when switching users. Perhaps something like "if output contains 'su: Sorry' and a test `su - $user /bin/true` prints any output at all, print a custom error message indicating a permissions issue"? That may just add meaningless complexity, though.

Either way, I am comfortable closing this unless others are experiencing the same issue. I'll leave it up to the maintainers to close or not.

**Comment by TheKevJames** [comment] 2016-11-23 20:43
Happy to see the issue is resolved for you!

I'm inclined to agree: we should probably look into handling that case, or at least look more closely into the relevant logic. I'll keep this open as low-priority and take a look in the future.

**Comment by kdubau** [comment] 2017-02-24 18:33
I am having the same exact issue. It only happens on 5-10 machines of about 25 (ElCap and Sierra).

If I go to a machine which is affected and execute the command `/usr/bin/su myuser -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"'` manually it succeeds. However if I run it as root (like my puppet agent service does), ie. `sudo /usr/bin/su xamarinqa -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"'` that I receive this error. 

Any ideas what I can dig into?

**Comment by jordigg** [comment] 2017-02-24 18:40
A full log of the run while running `puppet agent -t --verbose --debug --trace` would be really helpful.

**Comment by kdubau** [comment] 2017-02-24 21:28
I has to filter it unfortunately, but these are the only lines from this module.
```
[0;32mInfo: Applying configuration version '1487970525'[0m
[0;36mDebug: Exec[install-homebrew](provider=posix): Executing '/usr/bin/su ruggles -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"''[0m
[0;36mDebug: Executing: '/usr/bin/su ruggles -c '/bin/bash -o pipefail -c "/usr/bin/curl -skSfL https://github.com/homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1"''[0m
[mNotice: /Stage[main]/Homebrew::Install/Exec[install-homebrew]/returns: bin/brew: Can't create 'bin/brew'[0m
[mNotice: /Stage[main]/Homebrew::Install/Exec[install-homebrew]/returns: tar: Error exit delayed from previous errors.[0m
[mNotice: /Stage[main]/Homebrew::Install/File[/usr/local/bin/brew]: Dependency Exec[install-homebrew] has failures: true[0m
[0;36mDebug: /Stage[main]/Homebrew::Install/File[/usr/local/bin/brew]: Resource is being skipped, unscheduling all events[0m
[0;36mDebug: Class[Homebrew::Install]: Resource is being skipped, unscheduling all events[0m

[0;36mDebug: Stage[main]: Resource is being skipped, unscheduling all events[0m
[0;36mDebug: Finishing transaction 70109957580780[0m
[0;36mDebug: Storing state[0m
[0;36mDebug: Stored state in 0.03 seconds[0m
[mNotice: Applied catalog in 2.77 seconds[0m
[0;36mDebug: Dynamically-bound server lookup failed, falling back to report_server setting[0m
[0;36mDebug: Dynamically-bound port lookup failed; falling back to report_port setting[0m
[0;36mDebug: Using cached connection for https://ruggles-foreman.ruggles.local:8140[0m
[0;36mDebug: Caching connection for https://ruggles-foreman.ruggles.local:8140[0m
[0;36mDebug: Closing connection for https://ruggles-foreman.ruggles.local:8140[0m
```

**Comment by TheKevJames** [comment] 2017-02-25 07:56
Hey @kdubau could you just verify that `myuser` is `xamarinqa` in your first comment? Also could you clarify which user you were running each command as?

Looks like the first relevant error in that log is 

    Homebrew::Install/Exec[install-homebrew]/returns: bin/brew: Can't create 'bin/brew'

That looks like a permissions issue to me. Could you paste the output of

    ls -l /usr | grep local
    ls -l /usr/local | grep brew

Hopefully all of the above information will help us figure out what's going on here.

**Comment by kdubau** [comment] 2017-02-27 15:28
@TheKevJames Hey, yes my user is `xamarinqa`.

Output requested:
```
ruggles-capitan-4:local xamarinqa$ ls -l /usr | grep local
drwxrwxr-x    18 xamarinqa  staff    612 Feb 27 10:03 local
ruggles-capitan-4:local xamarinqa$ ls -l /usr/local | grep brew
drwxrwxr-x    2 xamarinqa  admin    68 Feb 24 13:00 Homebrew
```

Thanks!

**Comment by kdubau** [comment] 2017-02-28 15:15
I added this to my manifest and it resolved my issue.

```puppet
    File<|title == '/usr/local'|> {
        ensure  => directory,
        owner   => $user,
        group   => 'admin',
        mode    => '0775',
        recurse => true,
    }

**Comment by TheKevJames** [comment] 2017-02-28 15:20
Hmm, are you by chance using version 1.5.0 of this package? This looks similar to a bug we fixed in 1.6.0.

If so, could you update to 1.6.0 and check whether the issue persists?

**Comment by jordigg** [comment] 2017-02-28 16:29
This should already be fixed as @TheKevJames mentioned. If you are using latest could you let me know if you had homebrew installed before using this module?

We already change permissions on `/usr/local` but we don't do it recursively because there may be other tools there which may require `root:wheel` permissions.
https://github.com/TheKevJames/puppet-homebrew/blob/master/manifests/install.pp#L3-L23

**Comment by kdubau** [comment] 2017-02-28 16:42
I'm on latest yes. For some reason in my environment I needed to set `myuser:admin` on `/usr/local` - simply `:admin` like this module does was not enough.

**Comment by TheKevJames** [comment] 2017-02-28 18:06
Hmm, we might be able to set the user on https://github.com/TheKevJames/puppet-homebrew/blob/master/manifests/install.pp#L19-L23 explicitly. I wonder if this could cause any negative side-effects? Note I specifically mean adding `$homebrew::user` to this block and *not* changing anything about how it recurses.

I'm leaning towards "probably not", since my understanding is `/usr/local` is _supposed_ to by owned by `myuser:mygroup` anyway... thoughts?

**Comment by jordigg** [comment] 2017-02-28 18:09
I think that was the primary reason why homebrew moved from `/usr/local` to `/usr/local/Homebrew` because was messing with the permissions form other tools like postgresql or similar which require very specific permissions, user and groups.
By making the directory 755 and with an admin or similar group should avoid any of this issues. I tried on fresh machines and had 0 problems with this.
@kdubau would be possible to try on a VM or similar just in case you had that folder already messed up for another reason?

**Comment by kdubau** [comment] 2017-02-28 19:31
I can say with a decent amount of confidence that yes the folder was already messed up for another reasons. When developing I was using a clean VM and had no problems.

**Comment by TheKevJames** [comment] 2017-02-28 23:13
Cool, sounds like this is resolved to me then. Feel free to open up a new issue if you encounter any further issues.

**Closed by TheKevJames** 2017-02-28 23:13 UTC
Labels: bug, low-priority
